# How many violations should merit a temp-ban? (default: 5)
violations: 5

# How long should the ban last? (default: 7 [days])
ban-duration: 7

# What should the ban message be? (default: "&c{user}:&6 you have been temporarily banned for using &c{hack}&6. This ban lasts &c{time}&6 days.")
ban-message: "&c{user}:&6 you have been temporarily banned for using &c{hack}&6. This ban lasts &c{time}&6 days."

# Should the server ban by IP? (default: false)
ip-ban: false